# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-17 21:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import taggit_selectize.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_kategorii', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Kryptowaluta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_kryptowaluty', models.CharField(max_length=50)),
                ('kod_kryptowaluty', models.CharField(max_length=10)),
                ('informacje_dodatkowe', models.CharField(default='Strona internetowa', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_USER', models.IntegerField(default=0)),
                ('values', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Przelew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_USER', models.IntegerField(default=0)),
                ('nazwa_przelewu_text', models.CharField(max_length=70)),
                ('ilość_kryptowalut', models.DecimalField(decimal_places=4, max_digits=10)),
                ('zaplacono', models.DecimalField(decimal_places=4, max_digits=10)),
                ('data_tranzakcji', models.DateField(default=datetime.date.today, verbose_name='Data zakupu waluty')),
                ('widełki_min', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('widełki_max', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('kryptowaluta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kryptomain.Kryptowaluta')),
                ('kryptowaluta_zakupu', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='przelew_kryptowaluta_zakupu', to='kryptomain.Kryptowaluta')),
            ],
        ),
        migrations.CreateModel(
            name='TematycznyPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_autora', models.IntegerField(default=0)),
                ('data_wpisu', models.DateTimeField(default=datetime.datetime(2018, 6, 17, 23, 33, 28, 970698), verbose_name='data wpisu')),
                ('nazwa_postu', models.CharField(max_length=70)),
                ('text', models.TextField()),
                ('idkategorii', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kryptomain.Kategoria')),
                ('tags', taggit_selectize.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Waluta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_waluty', models.CharField(max_length=50)),
                ('kod_waluty', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='przelew',
            name='waluta_powiadomienia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='przelew_waluta_powiadomienia', to='kryptomain.Waluta'),
        ),
        migrations.AddField(
            model_name='przelew',
            name='waluta_zakupu',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='przelew_waluta_zakupu', to='kryptomain.Waluta'),
        ),
        migrations.AddField(
            model_name='like',
            name='idPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kryptomain.TematycznyPost'),
        ),
    ]
