# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-19 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kryptomain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booksraport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frDate', models.DateTimeField()),
                ('toDate', models.DateTimeField()),
                ('portfel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kryptomain.Portfel')),
            ],
        ),
    ]
