# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-20 15:43
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('kryptomain', '0002_auto_20180618_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tematycznypost',
            name='ID_autora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tematycznypost',
            name='data_wpisu',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 17, 43, 5, 706715), verbose_name='data wpisu'),
        ),
        migrations.AlterField(
            model_name='tematycznypost',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Tagi zaznaczamy przez przecinek', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
