# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-21 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kryptomain', '0002_booksraport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksraport',
            name='portfel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kryptomain.Portfel'),
        ),
    ]
