# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-26 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kryptomain', '0004_auto_20180326_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walut5a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_waluty', models.CharField(max_length=50)),
                ('kod_waluty', models.CharField(max_length=10)),
                ('Wartość_walut_PLN', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='przelew',
            name='kryptowaluta',
        ),
        migrations.RemoveField(
            model_name='przelew',
            name='waluta',
        ),
        migrations.DeleteModel(
            name='Kryptowaluta',
        ),
        migrations.DeleteModel(
            name='Przelew',
        ),
        migrations.DeleteModel(
            name='Waluta',
        ),
    ]
