# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-21 01:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kryptomain', '0004_auto_20180620_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentarz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wpisu', models.DateTimeField(default=datetime.datetime(2018, 6, 21, 3, 26, 41, 519790), verbose_name='data wpisu')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='tematycznypost',
            name='ID_autora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tematycznypost',
            name='data_wpisu',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 3, 26, 41, 518792), verbose_name='data wpisu'),
        ),
        migrations.AddField(
            model_name='komentarz',
            name='TematycznyPost',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kryptomain.TematycznyPost'),
        ),
        migrations.AddField(
            model_name='komentarz',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
