# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-26 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kryptomain', '0005_auto_20180326_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kryptowaluta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_kryptowaluty', models.CharField(max_length=50)),
                ('kod_kryptowaluty', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Przelew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_USER', models.IntegerField(default=0)),
                ('nazwa_przelewu_text', models.CharField(max_length=70)),
                ('ilość_kryptowalut', models.DecimalField(decimal_places=4, max_digits=10)),
                ('wartość_kryptowaluty', models.DecimalField(decimal_places=4, max_digits=10)),
                ('data_tranzakcji', models.DateTimeField(verbose_name='Data zakupu waluty')),
                ('kryptowaluta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kryptomain.Kryptowaluta')),
            ],
        ),
        migrations.CreateModel(
            name='Waluta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_waluty', models.CharField(max_length=50)),
                ('kod_waluty', models.CharField(max_length=10)),
                ('Wartość_walut_PLN', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Walut5a',
        ),
        migrations.AddField(
            model_name='przelew',
            name='waluta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kryptomain.Waluta'),
        ),
    ]
