# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-21 03:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kryptomain', '0005_auto_20180621_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentarz',
            name='TematycznyPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kryptomain.TematycznyPost'),
        ),
        migrations.AlterField(
            model_name='komentarz',
            name='data_wpisu',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 5, 0, 44, 587303), verbose_name='data wpisu'),
        ),
        migrations.AlterField(
            model_name='komentarz',
            name='text',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tematycznypost',
            name='data_wpisu',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 5, 0, 44, 586303), verbose_name='data wpisu'),
        ),
    ]
