# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 10:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('kryptomain', '0013_auto_20180621_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='przelew',
            old_name='ilość_kryptowalut',
            new_name='ilosc_kryptowalut',
        ),
        migrations.RenameField(
            model_name='przelew',
            old_name='widełki_max',
            new_name='widelki_max',
        ),
        migrations.RenameField(
            model_name='przelew',
            old_name='widełki_min',
            new_name='widelki_min',
        ),
        migrations.AlterField(
            model_name='komentarz',
            name='data_wpisu',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 23, 12, 27, 25, 26271), verbose_name='data wpisu'),
        ),
        migrations.AlterField(
            model_name='tematycznypost',
            name='data_wpisu',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 23, 12, 27, 25, 26271), verbose_name='data wpisu'),
        ),
        migrations.AlterField(
            model_name='tematycznypost',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
