# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 17:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kryptomain', '0016_auto_20180623_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentarz',
            name='data_wpisu',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 23, 19, 28, 18, 486209), verbose_name='data wpisu'),
        ),
        migrations.AlterField(
            model_name='tematycznypost',
            name='data_wpisu',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 23, 19, 28, 18, 484210), verbose_name='data wpisu'),
        ),
    ]
