# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 18:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kryptomain', '0017_auto_20180623_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentarz',
            name='data_wpisu',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 23, 20, 17, 5, 99071), verbose_name='data wpisu'),
        ),
        migrations.AlterField(
            model_name='tematycznypost',
            name='data_wpisu',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 23, 20, 17, 5, 98073), verbose_name='data wpisu'),
        ),
    ]
