# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 22:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kryptomain', '0019_auto_20180623_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentarz',
            name='data_wpisu',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 24, 0, 49, 33, 554483), verbose_name='data wpisu'),
        ),
        migrations.AlterField(
            model_name='tematycznypost',
            name='data_wpisu',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 24, 0, 49, 33, 553483), verbose_name='data wpisu'),
        ),
    ]
