# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 02:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kryptomain', '0040_auto_20180625_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='przelew',
            name='nieaktywny',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='komentarz',
            name='data_wpisu',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 27, 4, 39, 24, 408156), verbose_name='data wpisu'),
        ),
        migrations.AlterField(
            model_name='tematycznypost',
            name='data_wpisu',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 27, 4, 39, 24, 408156), verbose_name='data wpisu'),
        ),
    ]
