# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 16:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kryptomain', '0042_auto_20180627_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentarz',
            name='data_wpisu',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 27, 18, 31, 14, 266824), verbose_name='data wpisu'),
        ),
        migrations.AlterField(
            model_name='tematycznypost',
            name='data_wpisu',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 27, 18, 31, 14, 263824), verbose_name='data wpisu'),
        ),
    ]
